Add support for automatic token refresh
marmelab/ra-auth-msal pull request #7
Opened 2023-07-11 15:03 UTC by djhi

2023-07-11 16:02 UTC, slax57 requested changes
Other than that, lgtm.

Still gotta test though.

2023-07-11 16:23 UTC, slax57 commented
Tests look OK :heavy_check_mark:

2023-07-12 07:58 UTC, djhi commented on packages/ra-auth-msal/package.json
> +        "react-admin": "^4.7.0"
It's actually 4.9 minimum

2023-07-12 07:58 UTC, djhi commented on packages/ra-auth-msal/package.json
> +        "react-admin": "^4.12.1",
Because of yarn, I require `4.9.0` for the lib to work and `4.12.1` to have the latest in dev without conflicts with the demo app

2023-07-12 08:05 UTC, slax57 approved these changes

2023-07-12 08:07 UTC, merged